version : "3"

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/data  
    command: ["npm","run","dev","--","--host"]
    image: react_server:1.0
    container_name: react_dev 
    ports:
      - "5173:5173"
    volumes:
      - ./data:/opt/data